var_name_dict = {
    # daily variables
    "day-air-tmp-avg": "DayAirTmpAvg",
    "day-air-tmp-max": "DayAirTmpMax",
    "day-air-tmp-min": "DayAirTmpMin",
    "day-dew-pnt": "DayDewPnt",
    "day-eto": "DayEto",
    "day-asce-eto": "DayAsceEto",
    "day-asce-etr": "DayAsceEtr",
    "day-precip": "DayPrecip",
    "day-rel-hum-avg": "DayRelHumAvg",
    "day-rel-hum-max": "DayRelHumMax",
    "day-rel-hum-min": "DayRelHumMin",
    "day-soil-tmp-avg": "DaySoilTmpAvg",
    "day-soil-tmp-max": "DaySoilTmpMax",
    "day-soil-tmp-min": "DaySoilTmpMin",
    "day-sol-rad-avg": "DaySolRadAvg",
    "day-sol-rad-net": "DaySolRadNet",
    "day-vap-pres-max": "DayVapPresMax",
    "day-vap-pres-avg": "DayVapPresAvg",
    "day-wind-ene": "DayWindEne",
    "day-wind-ese": "DayWindEse",
    "day-wind-nne": "DayWindNne",
    "day-wind-nnw": "DayWindNnw",
    "day-wind-run": "DayWindRun",
    "day-wind-spd-avg": "DayWindSpdAvg",
    "day-wind-ssw": "DayWindSpdSsw",
    "day-wind-wnw": "DayWindSpdWnw",
    "day-wind-wsw": "DayWindSpdWsw",
    # hourly variables
    "hly-air-tmp": "HlyAirTmp",
    "hly-dew-pnt": "HlyDewPnt",
    "hly-eto": "HlyEto",
    "hly-net-rad": "HlyNetRad",
    "hly-asce-eto": "HlyAsceEto",
    "hly-asce-etr": "HlyAsceEtr",
    "precip": "Precip",
    "hly-rel-hum": "HlyRelHum",
    "hly-res-wind": "HlyResWind",
    "hly-soil-tmp": "HlySoilTmp",
    "hly-sol-rad": "HlySolRad",
    "hly-vap-pres": "HlyVapPres",
    "hly-wind-dir": "HlyWindDir",
    "hly-wind-spd": "HlyWindSpd",
}
